### ISSUE TITLE
No ground model for Zsh5 Helmet

### ISSUE THREAD

**Issue by ralian** [ralian/R3D_CORE#1]
Steps to reproduce:
1. Spawn arsenal and equip helmet
2. Place on ground

Need to find time to re-export a ground model in blender.

**Comment by BigBenDevs** [comment]
Zsh-5 ground item added awaiting review.

**Comment by BigBenDevs** [comment]
Fixed in
[Merge 3](https://github.com/ralian/R3D_CORE/pull/3)
