### ISSUE TITLE
Buoyancy Issue with 1.2

### ISSUE THREAD

**Issue by tanaaKa** [ralian/R3D_CORE#19]
The last reforger update that came out today has changed constructor structure:

`Constructor 'R3D_BuoyancyComponentClass', argument 'prefab' is not compatible with prototype argument type or spec 'IEntityComponentSource'`

**scripts/Game/Vehicles/Miscellaneous/R3D_BuoyancyComponentClass.c,26**:
![image](https://github.com/ralian/R3D_CORE/assets/9407533/d127cee7-a114-4c15-b5d2-5ce8c2f01ef4)

**Comment by ralian** [comment]
Thanks for reporting this - I somehow missed the issue at the time, but we did fix this a few days after the update.
