### ISSUE TITLE
R3D_FuelVehicleAction NULL pointer VME

### ISSUE THREAD

**Issue by BigBenDevs** [ralian/R3D_CORE#4]
Issue:

[Reported by @Mortalis Ares in Project Redline: CORE thread](https://discord.com/channels/105462288051380224/1106406416287272970/1150876525755904190)

Received this error message while using Redline: CORE
`11.09 2023 15:26:44
Virtual Machine Exception
Reason: NULL pointer to instance
Class:      'R3D_FuelVehicleAction'
Function: 'PerformAction'
Stack trace:
scripts/Game/Actions/R3D_FuelVehicleAction.c:45 Function PerformAction
Runtime mode`

Steps to reproduce: N/A

**Comment by ralian** [comment]
Will look into this before the next update, as well as try and get it working on dedicated.

**Comment by ralian** [comment]
This functionality is in vanilla now, so I removed this from core entirely.
